FROM kitware/trame:py3.12-uv

RUN apt-get update && apt-get install -y \
    libglu1-mesa-dev \
    libgl1-mesa-dev \
    libxrandr2 \
    libxinerama1 \
    libxcursor1 \
    libxi6

# Set working directory
WORKDIR /app

# Copy dependency files first (for better Docker layer caching)
COPY pyproject.toml uv.lock ./

# Install/update dependencies using UV
RUN uv sync --frozen

# Copy application code
COPY . .

# Run the Trame application
CMD ["khorium", "--server"]